theme: jekyll-theme-cayman

exclude: [ "Gemfile.lock", "Gemfile", "README.md", ".gitignore", ".gitattributes" ]
include: [ "_pages" ]

title: ProtoDef
description: Describe your protocol, and read it with ease

production_url: http://protodef.io
